# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

# platform :android do
#   desc "Runs all the tests"
#   lane :test do
#     gradle(task: "test")
#   end

#   desc "Submit a new Beta Build to Crashlytics Beta"
#   lane :beta do
#     gradle(task: "clean assembleRelease")
#     crashlytics

#     # sh "your_script.sh"
#     # You can also use other beta testing services here
#   end

#   desc "Deploy a new version to the Google Play"
#   lane :deploy do
#     gradle(task: "clean assembleRelease")
#     upload_to_play_store
#   end
# end


platform :android do
  desc "My awesome app"

  lane :increment_version do
    latest_release = firebase_app_distribution_get_latest_release(
      app: "1:667236950681:android:f8ce0e72b0f590d4d20e08"
    )
    increment_version_code({ version_code: latest_release[:buildVersion].to_i + 1 })
  end

  lane :distribute do
      build_android_app(
      task: "bundle",
      build_type: "Release"
      )

      firebase_app_distribution(
          app: "1:667236950681:android:f8ce0e72b0f590d4d20e08",
          service_credentials_file: "./juniduler-b444c54708af.json",
          testers: "hjy8697@gmail.com, noboundarya@gmail.com",
          release_notes: "release with fastlane",
          android_artifact_type: "AAB"
      )
  end
end